# Generated by Django 3.1.6 on 2021-02-12 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('display_name', models.CharField(blank=True, max_length=32, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
