# Generated by Django 3.1.6 on 2021-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20210212_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
